const tokens = require('./tokens');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./pages/**/*.{js,jsx}', './components/**/*.{js,jsx}', './lib/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#ffffff',
        background: '#f6f9ff',
        surface: '#f6f9ff',
        'surface-bright': '#f6f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4fc',
        'surface-container': '#e8eef6',
        'surface-container-high': '#e3e9f1',
        'surface-container-highest': '#dde3eb',
        'surface-variant': '#dde3eb',
        'surface-dim': '#d4dbe2',
        border: '#c7c4d8',
        'outline-variant': '#c7c4d8',
        outline: '#777587',
        accent: '#4f46e5',
        danger: tokens.colors.danger,
        success: tokens.colors.success,
        primary: '#3525cd',
        'primary-container': '#4f46e5',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#dad7ff',
        secondary: '#565e74',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#131b2e',
        'on-secondary-fixed-variant': '#3f465c',
        'on-surface': '#161c22',
        'on-surface-variant': '#464555',
        'on-background': '#161c22',
        muted: '#565e74',
        'warning-amber': '#f59e0b',
        'warning-bg': 'rgba(245, 158, 11, 0.08)',
        'navy-charcoal': '#0f172a',
        brand: {
          DEFAULT: tokens.colors.accent,
          charcoal: tokens.colors.surface,
          sage: tokens.colors.success,
          bg: tokens.colors.bg,
        },
        warning: tokens.colors.accent,
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['DM Sans', 'Inter', 'ui-sans-serif', 'sans-serif'],
        'headline-lg': ['DM Sans', 'Inter', 'ui-sans-serif', 'sans-serif'],
        'headline-md': ['DM Sans', 'Inter', 'ui-sans-serif', 'sans-serif'],
        'body-lg': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: tokens.spacing,
      boxShadow: {
        card: '0 24px 70px rgba(0, 0, 0, .24)',
      },
    },
  },
  plugins: [],
};
