export async function sendReportReadyEmail(email, resultUrl) {
    if (!process.env.BREVO_API_KEY)
        throw new Error('BREVO_API_KEY is not configured');
    const response = await fetch('https://api.brevo.com/v3/smtp/email', {
        method: 'POST',
        headers: {
            'api-key': process.env.BREVO_API_KEY,
            'content-type': 'application/json',
        },
        body: JSON.stringify({
            sender: { email: process.env.BREVO_FROM_EMAIL ?? 'reports@getleaselens.com.au', name: 'GetLeaseLens' },
            to: [{ email }],
            subject: 'Your lease analysis is ready',
            htmlContent: `<p>Your lease analysis is ready.</p><p><a href="${resultUrl}">Open your report</a></p><p>This report is a plain-English summary generated by AI. It is not legal advice.</p>`,
        }),
    });
    if (!response.ok)
        throw new Error('Brevo email failed');
}
